server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #请注意:不建议在没有服务器身份验证的情况下建立SSL连接。根据MySQL 5.5.45+、5.6.26+和5.7.6+的要求，如果不设置显式选项，则必须建立默认的SSL连接。您需要通过设置useSSL=false显式地禁用SSL，或者设置useSSL=true并为服务器证书验证提供信任存储
    url: jdbc:mysql://192.168.152.129:3306/tensquare_base?useUnicode=true&characterEncoding=utf-8&useSSL=false #增加安全性
    username: root
    password: root

  jpa:
    database: mysql
    show-sql: true




